packages:
  - 'apps/*'
  - 'libs/auth/auth-feature'
  - 'libs/auth/auth-util'
  - 'libs/auth/auth-ui'
  - 'libs/auth/auth-data-access'
  - 'libs/common/common-data-access'
  - 'libs/home/home-data-access'
  - 'libs/home/home-feature'
  - 'libs/home/home-ui'
  - 'libs/home/home-util'
  - 'libs/questionnaire/questionnaire-data-access'
  - 'libs/questionnaire/questionnaire-feature'
  - 'libs/questionnaire/questionnaire-ui'
  - 'libs/questionnaire/questionnaire-util'
  - 'libs/common/common-ui'
  - 'libs/address/address-feature'
  - 'libs/address/address-ui'
  - 'libs/address/address-util'
  - 'libs/address/address-data-access'
  - 'libs/contact/contact-data-access'
  - 'libs/contact/contact-ui'
  - 'libs/contact/contact-util'
  - 'libs/contact/contact-feature'
  - 'libs/profile/profile-feature'
  - 'libs/profile/profile-ui'
  - 'libs/beneficiary/beneficiary-data-access'
  - 'libs/beneficiary/beneficiary-feature'
  - 'libs/beneficiary/beneficiary-ui'
  - 'libs/beneficiary/beneficiary-util'
autoInstallPeers: true
strictPeerDependencies: false
